# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: pip install requests gitpython
  displayName: 'Installing required python modules'


- task: PythonScript@0
  inputs:
    scriptSource: 'filepath'
    scriptPath: 'generate-release-notes.py'
